releases/20160913115835/releases/20160912152214/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :chat_rooms, only: [:new, :create, :show, :index]
  root to: 'chat_rooms#index'
  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

releases/20160913115835/releases/20160912152214/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

releases/20160913115835/releases/20160912152214/app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
end

releases/20160913115835/releases/20160912152214/app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room
  validates :body, presence: true, length: {minimum: 2, maximum: 1000}
  after_create_commit { MessageBroadcastJob.perform_later(self) }

  def timestamp
    created_at.strftime('%H:%M:%S %d %B %Y')
  end


end 

releases/20160913115835/releases/20160912152214/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :chat_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy
  validates_uniqueness_of :email



  def name
    email.split('@')[0]
  end
end

releases/20160913115835/releases/20160912152214/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

 layout :layout_by_resource

  private

    def layout_by_resource
    if devise_controller?
      'devise'
    else
      'application'
    end
  end

end

releases/20160913115835/releases/20160912152214/app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  def index
    @chat_rooms = ChatRoom.all.order(:count).reverse
  end

  def new
    @chat_room = ChatRoom.new
  end

  def create
    @chat_room = current_user.chat_rooms.build(chat_room_params)
    if @chat_room.save
      flash[:success] = 'Chat room added!'
      redirect_to chat_rooms_path
    else
      render 'new'
    end
  end
  
  def show
    @chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
    @color = @chat_room.try(:color)
    @message = Message.new
  end 

  private

  def chat_room_params
    params.require(:chat_room).permit(:title, :count)
  end 
end

releases/20160913115835/releases/20160912152214/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

releases/20160913115835/releases/20160912152214/app/helpers/application_helper.rb
module ApplicationHelper
	def bootstrap_class_for flash_type
    	{ success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  	end

    def flash_messages(opts = {})
      flash.each do |msg_type, message|
        concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert') do
                 concat(content_tag(:button, class: 'close', data: { dismiss: 'alert' }) do
                          concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
                          concat content_tag(:span, 'Close', class: 'sr-only')
                 end)
                 concat message
        end)
      end
      nil
    end
end

releases/20160913115835/releases/20160912152214/app/helpers/chat_rooms_controller_helper.rb
module ChatRoomsControllerHelper
end

releases/20160913115835/releases/20160912152214/app/helpers/messages_helper.rb
module MessagesHelper
end

releases/20160913115835/releases/20160912152214/app/views/chat_rooms/_chat_room.html.erb
	<%= link_to chat_room_path(chat_room) do %>

	<div class="panel col-xs-12 col-md-2" id="tile" style="background-color: #<%=chat_room.color%>">

<h2 id="tile_title">

	<%= "#{chat_room.title.titleize}"%>
		
	<div class="text-muted">
		<%=chat_room.count%>
	</div>
</h2>
	
</div>

<% end %>

releases/20160913115835/releases/20160912152214/app/views/chat_rooms/index.html.erb
<h1>Chat rooms</h1>

<p class="lead"><%= link_to 'New chat room', new_chat_room_path, class: 'btn btn-primary' %></p>


  <%= render @chat_rooms %>



<div class="">





</div>

>

releases/20160913115835/releases/20160912152214/app/views/chat_rooms/new.html.erb
<h1>Add chat room</h1>

<%= bootstrap_form_for @chat_room do |f| %>
  <div class="form-group">
    <%= f.text_field :title, autofocus: true, class: 'form-control' %>
  </div>

  <%= f.submit "Add!", class: 'btn btn-primary' %>
<% end %>

releases/20160913115835/releases/20160912152214/app/views/chat_rooms/show.html.erb
<h1  id="chat_title"><%= @chat_room.title %></h1>
</br>
<div id="messages" data-chat-room-id="<%= @chat_room.id %>" style="background-color:#c1b4ae ;padding-left:10px">
  <%= render @chat_room.messages %>
</div>


<%= bootstrap_form_for @message, url: '#' do |f| %>
  <%= hidden_field_tag 'chat_room_id', @chat_room.id %>
  <div class="form-group" >
    <%= f.text_area :body, class: 'form-control', placeholder: 'From 2 to 1000 characters', id: "message_text_type" %>
   
  </div>

  <%= f.submit "Post", class: 'btn btn-primary btn-block visible-xs' %>
  <%= f.submit "Post", class: 'btn btn-primary btn-lg hidden-xs' %>
<% end %>

releases/20160913115835/releases/20160912152214/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ac</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
  <link href="https://fonts.googleapis.com/css?family=Oswald|Pacifico|Baloo+Paaji" rel="stylesheet"> 
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body   style="background-color: #<%= @color? @color : 'c1b4ae' %>;" >
      <nav class="navbar navbar-default navbar-fixed-top ">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to root_path, class: "navbar-brand" do %>
            Chat
          <% end %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <%= yield :right_nav %>

              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Settings", edit_user_registration_path %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <li><%= link_to "Login", new_user_session_path %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

<div id="gradient">
</br>
</br>
       <%= yield %>
    </div>
</div>
  </body>
</html>

releases/20160913115835/releases/20160912152214/app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ac</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
  <link href="https://fonts.googleapis.com/css?family=Oswald|Pacifico|Baloo+Paaji" rel="stylesheet"> 
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

 

<div id="gradient" class="container">

<div class="col-xs-12 col-md-offset-4 col-md-4">
  <%= yield %>
</div>
      

</div>
  </body>
</html>